[diagnosis]

# CPU使用率
cpu_caution = 80
cpu_warning = 95

# メモリ使用率
memory_caution = 80
memory_warning = 90

# ディスク使用率
disk_caution = 80
disk_warning = 90

# CPU温度
cpu_temperature_caution = 80
cpu_temperature_warning = 90


[retention]

# JSONログ保存期間（時間）
json_hours = 120

# HTMLレポート保存期間（時間）
html_hours = 120